apiVersion: v1
kind: ConfigMap
metadata:
  name: kardex-config
data:
  SPRING_CLOUD_CONFIG_URI: "http://config-service:8081"
  EUREKA_KARDEX_SERVICE_URL_DEFAULTZONE: "http://eureka-service:8761/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "kardex-service"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
