apiVersion: v1
kind: ConfigMap
metadata:
  name: client-service-config
data:
  SERVER_PORT: "0"
  SPRING_CLOUD_CONFIG_URI: "http://config-service:8081"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-service:8761/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "client-service"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/bd_microservice_client"
  SPRING_DATASOURCE_USERNAME: "diego"
  SPRING_DATASOURCE_PASSWORD: "diego1234"