apiVersion: v1
kind: ConfigMap
metadata:
  name: client-service-config
data:
  SERVER_PORT: "0"
  server-port: "0"
  config-server-uri: "http://config-service:8081"
  eureka-server-url: "http://eureka-service:8761/eureka/"
  # Configuraci√≥n de MySQL
  mysql-host: "mysql"
  mysql-database: "bd_microservice_client"