server:
  port: ${SERVER_PORT:8081}
spring:
  cloud:
    config:
      server:
        git:
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL:main}
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/DiegoRaAr/data-config-tingeso}
          search-paths: ${SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS:config-data}
  application:
    name: config-service