apiVersion: v1
kind: ConfigMap
metadata:
  name: tool-config
data:
  SPRING_CLOUD_CONFIG_URI: "http://config-service:8081"
  EUREKA_TOOL_SERVICE_URL_DEFAULTZONE: "http://eureka-service:8761/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "tool-service"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
