apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-service-config
data:
  server-port: "8761"
  config-server-uri: "http://config-service:8081"
  # Configuración específica de Eureka
  register-with-eureka: "false"
  fetch-registry: "false"